# Use an official Python runtime as a parent image
FROM python:3.10

# Install MLflow
RUN pip install mlflow

# Expose the MLflow server port
EXPOSE 5000

# Run MLflow server
CMD ["mlflow", "server", "--host", "0.0.0.0", "--port", "5000", "--backend-store-uri", "sqlite:///mlflow.db", "--default-artifact-root", "/mlflow/artifacts"]
