
services:
  streamlit:
    # This is for that asking the container to execute the main.py
    # command: sleep infinity 
    # The image I upload to my docker hub
    image: ponkrit_a2/streamlitbuild_v5:latest
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    #port of docker
    # 8000:localhost -> 8501:docker
    ports: #port mapping or forwarding port
      - "8000:8501" 
    # volumes:
    #   - ./streamlit:/streamlit
    # # For MAC M1 user
    # platform: windows/x86_64
    # This will ask DASH to run on 0.0.0.0 and port 8501
    environment:
      # - HOST=0.0.0.0
      # - PORT=80
      - STREAMLIT_DEBUG=True
    # This is important for asking Traefik to use your container.
    labels:
      # Allow Traefik to talk with your service
      - traefik.enable=true
      # Tell Traefik to use port 80
      - traefik.http.services.web-st124960-st124960.loadbalancer.server.port=8501
      # This config you domain name. By default, your subdomain is <service_name>-<folder_name>
      # If you which to change the subdomain name, you uncomment the below configuration
      - traefik.http.routers.web-st124960-st124960.rule=Host(`st124960.ml.brain.cs.ait.ac.th`)
      # Below is for enable SSL.
      - traefik.http.routers.web-st124960-st124960.tls=true
      - traefik.http.routers.web-st124960-st124960.tls.certresolver=production
      - traefik.http.routers.web-st124960-st124960.entrypoints=websecure
    # This define network. You would need to keep it like this.
    networks:
      - default
      - traefik_default

# Keep it like this too.
networks:
  default:
  traefik_default:
    external: true